{
    "name": "LLM Agent",
    "version": "16.0.1.0.0",
    "category": "Productivity",
    "summary": "LLM Agent for Odoo",
    "author": "Apex Labs",
    "website": "https://apexive.com",
    "license": "LGPL-3",
    "depends": ["base", "mail", "llm"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/agent_views.xml",
        "views/llm_agent_config_views.xml",
        "views/create_agent_wizard_views.xml",
        "views/llm_agent_task_views.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
